from pathlib import Path
import os

PROJECT_NAME = "veezo-mfn-platform"

FILES = {'.github/workflows/ci.yml': 'name: CI\n'
                             '\n'
                             'on:\n'
                             '  push:\n'
                             '    branches: [main, develop]\n'
                             '  pull_request:\n'
                             '    branches: [main]\n'
                             '\n'
                             'jobs:\n'
                             '  api:\n'
                             '    runs-on: ubuntu-latest\n'
                             '    defaults:\n'
                             '      run:\n'
                             '        working-directory: services/api\n'
                             '    steps:\n'
                             '      - uses: actions/checkout@v4\n'
                             '      - uses: actions/setup-node@v4\n'
                             '        with:\n'
                             '          node-version: 22\n'
                             '      - run: npm install\n'
                             '      - run: npm run typecheck\n'
                             '\n'
                             '  admin:\n'
                             '    runs-on: ubuntu-latest\n'
                             '    defaults:\n'
                             '      run:\n'
                             '        working-directory: apps/admin\n'
                             '    steps:\n'
                             '      - uses: actions/checkout@v4\n'
                             '      - uses: actions/setup-node@v4\n'
                             '        with:\n'
                             '          node-version: 22\n'
                             '      - run: npm install\n'
                             '      - run: npm run build\n',
 '.gitignore': '# Environment\n'
               '.env\n'
               '.env.*\n'
               '!.env.example\n'
               '\n'
               '# Node\n'
               'node_modules/\n'
               'dist/\n'
               '.next/\n'
               '\n'
               '# Flutter / Dart\n'
               '.dart_tool/\n'
               '.packages\n'
               '.pub-cache/\n'
               'build/\n'
               '.flutter-plugins\n'
               '.flutter-plugins-dependencies\n'
               '.metadata\n'
               '\n'
               '# IDE\n'
               '.vscode/\n'
               '.idea/\n'
               '*.iml\n'
               '\n'
               '# OS\n'
               '.DS_Store\n'
               'Thumbs.db\n'
               '\n'
               '# Secrets\n'
               '*.pem\n'
               '*.key\n'
               '*.p12\n'
               '*.jks\n'
               'google-services.json\n'
               'GoogleService-Info.plist\n',
 'README.md': '# Veezo MFN\n'
              '\n'
              'Veezo MFN is a UAE-focused live-streaming social platform starter repository.\n'
              '\n'
              '## What is included\n'
              '\n'
              '- Flutter mobile app scaffold\n'
              '- Node.js / NestJS-style API scaffold\n'
              '- PostgreSQL database schema\n'
              '- Redis-ready architecture\n'
              '- Admin dashboard placeholder\n'
              '- Docker Compose for local Postgres + Redis\n'
              '- GitHub Actions CI\n'
              '- Fake/test coin wallet architecture\n'
              '- Gift and creator earnings data model\n'
              '- Documentation for payments, moderation, and roadmap\n'
              '\n'
              '> Important: Real-money purchases and creator payouts are intentionally NOT enabled in this starter.\n'
              '> Complete UAE legal/compliance review before connecting live payment rails.\n'
              '\n'
              '## Repository structure\n'
              '\n'
              '```text\n'
              'veezo-mfn-platform/\n'
              '├── apps/\n'
              '│   ├── mobile/\n'
              '│   └── admin/\n'
              '├── services/\n'
              '│   └── api/\n'
              '├── database/\n'
              '├── docs/\n'
              '├── infrastructure/\n'
              '└── .github/workflows/\n'
              '```\n'
              '\n'
              '## Quick start\n'
              '\n'
              '### 1. Start database services\n'
              '\n'
              '```bash\n'
              'docker compose up -d\n'
              '```\n'
              '\n'
              '### 2. Start API\n'
              '\n'
              '```bash\n'
              'cd services/api\n'
              'npm install\n'
              'cp .env.example .env\n'
              'npm run start:dev\n'
              '```\n'
              '\n'
              '### 3. Start Flutter app\n'
              '\n'
              'Install Flutter first, then:\n'
              '\n'
              '```bash\n'
              'cd apps/mobile\n'
              'flutter pub get\n'
              'flutter run\n'
              '```\n'
              '\n'
              '### 4. Admin app\n'
              '\n'
              '```bash\n'
              'cd apps/admin\n'
              'npm install\n'
              'npm run dev\n'
              '```\n'
              '\n'
              '## First milestone\n'
              '\n'
              'The starter is designed for this V0.1 flow:\n'
              '\n'
              '```text\n'
              'Register/Login\n'
              '→ Discover creators\n'
              '→ Open fake live room\n'
              '→ Receive test coins\n'
              '→ Send virtual gift\n'
              '→ Deduct viewer coins\n'
              '→ Add creator test rewards\n'
              '→ Record transaction in ledger\n'
              '```\n'
              '\n'
              '## Planned integrations\n'
              '\n'
              '- Agora live streaming\n'
              '- Firebase push notifications\n'
              '- Supabase/Auth or custom JWT auth\n'
              '- Google Play Billing\n'
              '- Apple StoreKit\n'
              '- Stripe web checkout\n'
              '- Creator KYC provider\n'
              '- UAE payout provider\n'
              '- Automated moderation\n'
              '\n'
              '## Security\n'
              '\n'
              'Never commit:\n'
              '- API keys\n'
              '- private keys\n'
              '- certificates\n'
              '- database passwords\n'
              '- Stripe secret keys\n'
              '- Apple certificates\n'
              '- Google service-account files\n'
              '\n'
              'Use environment variables and GitHub Secrets.\n',
 'apps/admin/app/layout.js': 'export const metadata = {\n'
                             '  title: "Veezo MFN Admin",\n'
                             '  description: "Administration and moderation dashboard",\n'
                             '};\n'
                             '\n'
                             'export default function RootLayout({ children }) {\n'
                             '  return (\n'
                             '    <html lang="en">\n'
                             '      <body style={{ fontFamily: "Arial, sans-serif", margin: 0 }}>\n'
                             '        {children}\n'
                             '      </body>\n'
                             '    </html>\n'
                             '  );\n'
                             '}\n',
 'apps/admin/app/page.js': 'const cards = [\n'
                           '  ["Live Streams", "0"],\n'
                           '  ["Active Users", "0"],\n'
                           '  ["Open Reports", "0"],\n'
                           '  ["Pending Creator KYC", "0"],\n'
                           '  ["Gift Transactions", "0"],\n'
                           '  ["Pending Payouts", "0"],\n'
                           '];\n'
                           '\n'
                           'export default function AdminHome() {\n'
                           '  return (\n'
                           '    <main style={{ padding: 32, maxWidth: 1100, margin: "0 auto" }}>\n'
                           '      <h1>Veezo MFN Admin</h1>\n'
                           '      <p>V0.1 moderation and operations dashboard scaffold.</p>\n'
                           '\n'
                           '      <div\n'
                           '        style={{\n'
                           '          display: "grid",\n'
                           '          gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",\n'
                           '          gap: 16,\n'
                           '          marginTop: 24,\n'
                           '        }}\n'
                           '      >\n'
                           '        {cards.map(([label, value]) => (\n'
                           '          <section\n'
                           '            key={label}\n'
                           '            style={{\n'
                           '              border: "1px solid #ddd",\n'
                           '              borderRadius: 12,\n'
                           '              padding: 20,\n'
                           '            }}\n'
                           '          >\n'
                           '            <div style={{ fontSize: 14 }}>{label}</div>\n'
                           '            <div style={{ fontSize: 32, fontWeight: 700 }}>{value}</div>\n'
                           '          </section>\n'
                           '        ))}\n'
                           '      </div>\n'
                           '\n'
                           '      <section style={{ marginTop: 32 }}>\n'
                           '        <h2>Build order</h2>\n'
                           '        <ol>\n'
                           '          <li>User management</li>\n'
                           '          <li>Creator approvals</li>\n'
                           '          <li>Live stream monitoring</li>\n'
                           '          <li>Reports and bans</li>\n'
                           '          <li>Coin and gift ledger</li>\n'
                           '          <li>Creator earnings and payouts</li>\n'
                           '        </ol>\n'
                           '      </section>\n'
                           '    </main>\n'
                           '  );\n'
                           '}\n',
 'apps/admin/package.json': '{\n'
                            '  "name": "@veezo/admin",\n'
                            '  "version": "0.1.0",\n'
                            '  "private": true,\n'
                            '  "scripts": {\n'
                            '    "dev": "next dev",\n'
                            '    "build": "next build",\n'
                            '    "start": "next start"\n'
                            '  },\n'
                            '  "dependencies": {\n'
                            '    "next": "^15.1.0",\n'
                            '    "react": "^19.0.0",\n'
                            '    "react-dom": "^19.0.0"\n'
                            '  }\n'
                            '}\n',
 'apps/mobile/README.md': '# Veezo MFN Mobile\n'
                          '\n'
                          'This folder contains the Flutter application code.\n'
                          '\n'
                          'If this repository was uploaded manually and native Flutter platform folders are missing, '
                          'run this command once inside `apps/mobile`:\n'
                          '\n'
                          '```bash\n'
                          'flutter create --org ae.veezomfn --platforms=android,ios .\n'
                          '```\n'
                          '\n'
                          'Flutter will generate Android/iOS platform folders while preserving the existing `lib/` '
                          'code and `pubspec.yaml`.\n'
                          '\n'
                          'Then run:\n'
                          '\n'
                          '```bash\n'
                          'flutter pub get\n'
                          'flutter run\n'
                          '```\n',
 'apps/mobile/lib/main.dart': "import 'package:flutter/material.dart';\n"
                              "import 'package:flutter_riverpod/flutter_riverpod.dart';\n"
                              "import 'src/app.dart';\n"
                              '\n'
                              'void main() {\n'
                              '  runApp(\n'
                              '    const ProviderScope(\n'
                              '      child: VeezoApp(),\n'
                              '    ),\n'
                              '  );\n'
                              '}\n',
 'apps/mobile/lib/src/app.dart': "import 'package:flutter/material.dart';\n"
                                 "import 'router.dart';\n"
                                 "import 'theme.dart';\n"
                                 '\n'
                                 'class VeezoApp extends StatelessWidget {\n'
                                 '  const VeezoApp({super.key});\n'
                                 '\n'
                                 '  @override\n'
                                 '  Widget build(BuildContext context) {\n'
                                 '    return MaterialApp.router(\n'
                                 "      title: 'Veezo MFN',\n"
                                 '      debugShowCheckedModeBanner: false,\n'
                                 '      theme: VeezoTheme.light,\n'
                                 '      darkTheme: VeezoTheme.dark,\n'
                                 '      routerConfig: router,\n'
                                 '    );\n'
                                 '  }\n'
                                 '}\n',
 'apps/mobile/lib/src/features/auth/login_screen.dart': "import 'package:flutter/material.dart';\n"
                                                        "import 'package:go_router/go_router.dart';\n"
                                                        '\n'
                                                        'class LoginScreen extends StatelessWidget {\n'
                                                        '  const LoginScreen({super.key});\n'
                                                        '\n'
                                                        '  @override\n'
                                                        '  Widget build(BuildContext context) {\n'
                                                        '    return Scaffold(\n'
                                                        '      body: SafeArea(\n'
                                                        '        child: Padding(\n'
                                                        '          padding: const EdgeInsets.all(24),\n'
                                                        '          child: Column(\n'
                                                        '            crossAxisAlignment: CrossAxisAlignment.stretch,\n'
                                                        '            children: [\n'
                                                        '              const Spacer(),\n'
                                                        '              Text(\n'
                                                        "                'Veezo MFN',\n"
                                                        '                textAlign: TextAlign.center,\n'
                                                        '                style: '
                                                        'Theme.of(context).textTheme.displaySmall?.copyWith(\n'
                                                        '                  fontWeight: FontWeight.w800,\n'
                                                        '                ),\n'
                                                        '              ),\n'
                                                        '              const SizedBox(height: 8),\n'
                                                        '              const Text(\n'
                                                        "                'Live. Connect. Reward creators.',\n"
                                                        '                textAlign: TextAlign.center,\n'
                                                        '              ),\n'
                                                        '              const SizedBox(height: 32),\n'
                                                        '              TextField(\n'
                                                        '                decoration: const InputDecoration(\n'
                                                        "                  labelText: 'Email or mobile',\n"
                                                        '                  border: OutlineInputBorder(),\n'
                                                        '                ),\n'
                                                        '              ),\n'
                                                        '              const SizedBox(height: 12),\n'
                                                        '              FilledButton(\n'
                                                        "                onPressed: () => context.go('/home'),\n"
                                                        "                child: const Text('Continue'),\n"
                                                        '              ),\n'
                                                        '              const SizedBox(height: 8),\n'
                                                        '              OutlinedButton(\n'
                                                        "                onPressed: () => context.go('/home'),\n"
                                                        "                child: const Text('Continue as demo user'),\n"
                                                        '              ),\n'
                                                        '              const Spacer(),\n'
                                                        '              const Text(\n'
                                                        "                'Demo build — real payments are disabled.',\n"
                                                        '                textAlign: TextAlign.center,\n'
                                                        '              ),\n'
                                                        '            ],\n'
                                                        '          ),\n'
                                                        '        ),\n'
                                                        '      ),\n'
                                                        '    );\n'
                                                        '  }\n'
                                                        '}\n',
 'apps/mobile/lib/src/features/home/home_screen.dart': "import 'package:flutter/material.dart';\n"
                                                       "import 'package:go_router/go_router.dart';\n"
                                                       '\n'
                                                       'class DemoCreator {\n'
                                                       '  final String name;\n'
                                                       '  final String city;\n'
                                                       '  final String language;\n'
                                                       '  final int viewers;\n'
                                                       '\n'
                                                       '  const DemoCreator(this.name, this.city, this.language, '
                                                       'this.viewers);\n'
                                                       '}\n'
                                                       '\n'
                                                       'const creators = [\n'
                                                       "  DemoCreator('Sara', 'Dubai', 'Arabic', 1248),\n"
                                                       "  DemoCreator('Noor', 'Abu Dhabi', 'English', 835),\n"
                                                       "  DemoCreator('Aisha', 'Sharjah', 'Malayalam', 642),\n"
                                                       "  DemoCreator('Riya', 'Dubai', 'Hindi', 516),\n"
                                                       '];\n'
                                                       '\n'
                                                       'class HomeScreen extends StatelessWidget {\n'
                                                       '  const HomeScreen({super.key});\n'
                                                       '\n'
                                                       '  @override\n'
                                                       '  Widget build(BuildContext context) {\n'
                                                       '    return Scaffold(\n'
                                                       '      appBar: AppBar(\n'
                                                       '        title: const Text(\n'
                                                       "          'Veezo MFN',\n"
                                                       '          style: TextStyle(fontWeight: FontWeight.w800),\n'
                                                       '        ),\n'
                                                       '        actions: [\n'
                                                       '          TextButton.icon(\n'
                                                       "            onPressed: () => context.push('/coins'),\n"
                                                       '            icon: const Icon(Icons.monetization_on_outlined),\n'
                                                       "            label: const Text('100'),\n"
                                                       '          ),\n'
                                                       '          const SizedBox(width: 8),\n'
                                                       '        ],\n'
                                                       '      ),\n'
                                                       '      body: ListView(\n'
                                                       '        padding: const EdgeInsets.all(16),\n'
                                                       '        children: [\n'
                                                       '          const Text(\n'
                                                       "            'Live Now',\n"
                                                       '            style: TextStyle(fontSize: 24, fontWeight: '
                                                       'FontWeight.w800),\n'
                                                       '          ),\n'
                                                       '          const SizedBox(height: 12),\n'
                                                       '          Wrap(\n'
                                                       '            spacing: 8,\n'
                                                       '            runSpacing: 8,\n'
                                                       '            children: const [\n'
                                                       "              Chip(label: Text('For You')),\n"
                                                       "              Chip(label: Text('UAE')),\n"
                                                       "              Chip(label: Text('Arabic')),\n"
                                                       "              Chip(label: Text('English')),\n"
                                                       "              Chip(label: Text('Hindi')),\n"
                                                       "              Chip(label: Text('Urdu')),\n"
                                                       "              Chip(label: Text('Malayalam')),\n"
                                                       '            ],\n'
                                                       '          ),\n'
                                                       '          const SizedBox(height: 16),\n'
                                                       '          ...creators.map(\n'
                                                       '            (creator) => Card(\n'
                                                       '              child: ListTile(\n'
                                                       '                leading: CircleAvatar(\n'
                                                       '                  child: Text(creator.name.substring(0, 1)),\n'
                                                       '                ),\n'
                                                       '                title: Row(\n'
                                                       '                  children: [\n'
                                                       '                    Expanded(child: Text(creator.name)),\n'
                                                       '                    const Text(\n'
                                                       "                      'LIVE',\n"
                                                       '                      style: TextStyle(\n'
                                                       '                        fontWeight: FontWeight.w800,\n'
                                                       '                      ),\n'
                                                       '                    ),\n'
                                                       '                  ],\n'
                                                       '                ),\n'
                                                       '                subtitle: Text(\n'
                                                       "                  '${creator.city} • ${creator.language} • "
                                                       "${creator.viewers} viewers',\n"
                                                       '                ),\n'
                                                       '                trailing: const Icon(Icons.chevron_right),\n'
                                                       '                onTap: () => '
                                                       "context.push('/live/${creator.name}'),\n"
                                                       '              ),\n'
                                                       '            ),\n'
                                                       '          ),\n'
                                                       '        ],\n'
                                                       '      ),\n'
                                                       '      bottomNavigationBar: NavigationBar(\n'
                                                       '        selectedIndex: 0,\n'
                                                       '        destinations: const [\n'
                                                       '          NavigationDestination(icon: '
                                                       "Icon(Icons.home_outlined), label: 'Home'),\n"
                                                       '          NavigationDestination(icon: '
                                                       "Icon(Icons.explore_outlined), label: 'Explore'),\n"
                                                       '          NavigationDestination(icon: '
                                                       "Icon(Icons.add_circle_outline), label: 'Live'),\n"
                                                       '          NavigationDestination(icon: '
                                                       "Icon(Icons.mail_outline), label: 'Inbox'),\n"
                                                       '          NavigationDestination(icon: '
                                                       "Icon(Icons.person_outline), label: 'Me'),\n"
                                                       '        ],\n'
                                                       '      ),\n'
                                                       '    );\n'
                                                       '  }\n'
                                                       '}\n',
 'apps/mobile/lib/src/features/live/live_room_screen.dart': "import 'package:flutter/material.dart';\n"
                                                            '\n'
                                                            'class LiveRoomScreen extends StatefulWidget {\n'
                                                            '  final String creatorName;\n'
                                                            '\n'
                                                            '  const LiveRoomScreen({\n'
                                                            '    super.key,\n'
                                                            '    required this.creatorName,\n'
                                                            '  });\n'
                                                            '\n'
                                                            '  @override\n'
                                                            '  State<LiveRoomScreen> createState() => '
                                                            '_LiveRoomScreenState();\n'
                                                            '}\n'
                                                            '\n'
                                                            'class _LiveRoomScreenState extends State<LiveRoomScreen> '
                                                            '{\n'
                                                            '  int coins = 100;\n'
                                                            "  String lastGift = '';\n"
                                                            '\n'
                                                            '  void sendGift(String name, int cost) {\n'
                                                            '    if (coins < cost) {\n'
                                                            '      ScaffoldMessenger.of(context).showSnackBar(\n'
                                                            "        const SnackBar(content: Text('Not enough test "
                                                            "coins')),\n"
                                                            '      );\n'
                                                            '      return;\n'
                                                            '    }\n'
                                                            '\n'
                                                            '    setState(() {\n'
                                                            '      coins -= cost;\n'
                                                            "      lastGift = '$name sent!';\n"
                                                            '    });\n'
                                                            '  }\n'
                                                            '\n'
                                                            '  @override\n'
                                                            '  Widget build(BuildContext context) {\n'
                                                            '    return Scaffold(\n'
                                                            '      backgroundColor: Colors.black,\n'
                                                            '      body: SafeArea(\n'
                                                            '        child: Stack(\n'
                                                            '          children: [\n'
                                                            '            const Positioned.fill(\n'
                                                            '              child: Center(\n'
                                                            '                child: Icon(\n'
                                                            '                  Icons.videocam_outlined,\n'
                                                            '                  size: 120,\n'
                                                            '                  color: Colors.white24,\n'
                                                            '                ),\n'
                                                            '              ),\n'
                                                            '            ),\n'
                                                            '            Positioned(\n'
                                                            '              top: 12,\n'
                                                            '              left: 12,\n'
                                                            '              right: 12,\n'
                                                            '              child: Row(\n'
                                                            '                children: [\n'
                                                            '                  CircleAvatar(child: '
                                                            'Text(widget.creatorName[0])),\n'
                                                            '                  const SizedBox(width: 8),\n'
                                                            '                  Expanded(\n'
                                                            '                    child: Text(\n'
                                                            '                      widget.creatorName,\n'
                                                            '                      style: const TextStyle(\n'
                                                            '                        color: Colors.white,\n'
                                                            '                        fontWeight: FontWeight.w700,\n'
                                                            '                      ),\n'
                                                            '                    ),\n'
                                                            '                  ),\n'
                                                            '                  FilledButton.tonal(\n'
                                                            '                    onPressed: () {},\n'
                                                            "                    child: const Text('Follow'),\n"
                                                            '                  ),\n'
                                                            '                  IconButton(\n'
                                                            '                    onPressed: () => '
                                                            'Navigator.of(context).pop(),\n'
                                                            '                    icon: const Icon(Icons.close, color: '
                                                            'Colors.white),\n'
                                                            '                  ),\n'
                                                            '                ],\n'
                                                            '              ),\n'
                                                            '            ),\n'
                                                            '            Positioned(\n'
                                                            '              left: 16,\n'
                                                            '              bottom: 110,\n'
                                                            '              child: Column(\n'
                                                            '                crossAxisAlignment: '
                                                            'CrossAxisAlignment.start,\n'
                                                            '                children: [\n'
                                                            "                  const Text('Ahmed: Hello 👋', style: "
                                                            'TextStyle(color: Colors.white)),\n'
                                                            "                  const Text('Maya: Amazing ❤️', style: "
                                                            'TextStyle(color: Colors.white)),\n'
                                                            '                  if (lastGift.isNotEmpty)\n'
                                                            '                    Text(\n'
                                                            '                      lastGift,\n'
                                                            '                      style: const TextStyle(\n'
                                                            '                        color: Colors.amber,\n'
                                                            '                        fontWeight: FontWeight.w700,\n'
                                                            '                      ),\n'
                                                            '                    ),\n'
                                                            '                ],\n'
                                                            '              ),\n'
                                                            '            ),\n'
                                                            '            Positioned(\n'
                                                            '              left: 12,\n'
                                                            '              right: 12,\n'
                                                            '              bottom: 20,\n'
                                                            '              child: Row(\n'
                                                            '                children: [\n'
                                                            '                  Expanded(\n'
                                                            '                    child: TextField(\n'
                                                            '                      style: const TextStyle(color: '
                                                            'Colors.white),\n'
                                                            '                      decoration: InputDecoration(\n'
                                                            "                        hintText: 'Say something...',\n"
                                                            '                        hintStyle: const TextStyle(color: '
                                                            'Colors.white70),\n'
                                                            '                        filled: true,\n'
                                                            '                        fillColor: Colors.white12,\n'
                                                            '                        border: OutlineInputBorder(\n'
                                                            '                          borderRadius: '
                                                            'BorderRadius.circular(30),\n'
                                                            '                          borderSide: BorderSide.none,\n'
                                                            '                        ),\n'
                                                            '                      ),\n'
                                                            '                    ),\n'
                                                            '                  ),\n'
                                                            '                  const SizedBox(width: 8),\n'
                                                            '                  FilledButton.icon(\n'
                                                            '                    onPressed: () => '
                                                            '_showGiftSheet(context),\n'
                                                            '                    icon: const '
                                                            'Icon(Icons.card_giftcard),\n'
                                                            "                    label: Text('$coins'),\n"
                                                            '                  ),\n'
                                                            '                ],\n'
                                                            '              ),\n'
                                                            '            ),\n'
                                                            '          ],\n'
                                                            '        ),\n'
                                                            '      ),\n'
                                                            '    );\n'
                                                            '  }\n'
                                                            '\n'
                                                            '  void _showGiftSheet(BuildContext context) {\n'
                                                            '    showModalBottomSheet(\n'
                                                            '      context: context,\n'
                                                            '      showDragHandle: true,\n'
                                                            '      builder: (_) => Padding(\n'
                                                            '        padding: const EdgeInsets.fromLTRB(16, 0, 16, '
                                                            '24),\n'
                                                            '        child: Column(\n'
                                                            '          mainAxisSize: MainAxisSize.min,\n'
                                                            '          children: [\n'
                                                            "            Text('Test balance: $coins coins'),\n"
                                                            '            const SizedBox(height: 12),\n'
                                                            '            Wrap(\n'
                                                            '              spacing: 10,\n'
                                                            '              runSpacing: 10,\n'
                                                            '              children: [\n'
                                                            "                _giftButton('❤️ Heart', 10),\n"
                                                            "                _giftButton('🌹 Rose', 50),\n"
                                                            "                _giftButton('☕ Coffee', 100),\n"
                                                            '              ],\n'
                                                            '            ),\n'
                                                            '          ],\n'
                                                            '        ),\n'
                                                            '      ),\n'
                                                            '    );\n'
                                                            '  }\n'
                                                            '\n'
                                                            '  Widget _giftButton(String name, int cost) {\n'
                                                            '    return FilledButton.tonal(\n'
                                                            '      onPressed: () {\n'
                                                            '        Navigator.pop(context);\n'
                                                            '        sendGift(name, cost);\n'
                                                            '      },\n'
                                                            "      child: Text('$name • $cost'),\n"
                                                            '    );\n'
                                                            '  }\n'
                                                            '}\n',
 'apps/mobile/lib/src/features/wallet/coin_store_screen.dart': "import 'package:flutter/material.dart';\n"
                                                               '\n'
                                                               'class CoinStoreScreen extends StatelessWidget {\n'
                                                               '  const CoinStoreScreen({super.key});\n'
                                                               '\n'
                                                               '  static const packages = [\n'
                                                               '    (350, 5),\n'
                                                               '    (750, 10),\n'
                                                               '    (1550, 20),\n'
                                                               '    (3200, 40),\n'
                                                               '    (8500, 100),\n'
                                                               '    (22500, 250),\n'
                                                               '    (47000, 500),\n'
                                                               '  ];\n'
                                                               '\n'
                                                               '  @override\n'
                                                               '  Widget build(BuildContext context) {\n'
                                                               '    return Scaffold(\n'
                                                               "      appBar: AppBar(title: const Text('Get Coins')),\n"
                                                               '      body: ListView.separated(\n'
                                                               '        padding: const EdgeInsets.all(16),\n'
                                                               '        itemCount: packages.length,\n'
                                                               '        separatorBuilder: (_, __) => const '
                                                               'SizedBox(height: 8),\n'
                                                               '        itemBuilder: (_, index) {\n'
                                                               '          final item = packages[index];\n'
                                                               '          return Card(\n'
                                                               '            child: ListTile(\n'
                                                               '              leading: const '
                                                               'Icon(Icons.monetization_on),\n'
                                                               "              title: Text('${item.$1} Coins'),\n"
                                                               '              trailing: FilledButton(\n'
                                                               '                onPressed: () {\n'
                                                               '                  '
                                                               'ScaffoldMessenger.of(context).showSnackBar(\n'
                                                               '                    const SnackBar(\n'
                                                               "                      content: Text('Payments are "
                                                               "disabled in V0.1'),\n"
                                                               '                    ),\n'
                                                               '                  );\n'
                                                               '                },\n'
                                                               "                child: Text('AED ${item.$2}'),\n"
                                                               '              ),\n'
                                                               '            ),\n'
                                                               '          );\n'
                                                               '        },\n'
                                                               '      ),\n'
                                                               '    );\n'
                                                               '  }\n'
                                                               '}\n',
 'apps/mobile/lib/src/router.dart': "import 'package:go_router/go_router.dart';\n"
                                    "import 'features/auth/login_screen.dart';\n"
                                    "import 'features/home/home_screen.dart';\n"
                                    "import 'features/live/live_room_screen.dart';\n"
                                    "import 'features/wallet/coin_store_screen.dart';\n"
                                    '\n'
                                    'final router = GoRouter(\n'
                                    "  initialLocation: '/login',\n"
                                    '  routes: [\n'
                                    '    GoRoute(\n'
                                    "      path: '/login',\n"
                                    '      builder: (_, __) => const LoginScreen(),\n'
                                    '    ),\n'
                                    '    GoRoute(\n'
                                    "      path: '/home',\n"
                                    '      builder: (_, __) => const HomeScreen(),\n'
                                    '    ),\n'
                                    '    GoRoute(\n'
                                    "      path: '/live/:creator',\n"
                                    '      builder: (_, state) => LiveRoomScreen(\n'
                                    "        creatorName: state.pathParameters['creator'] ?? 'Creator',\n"
                                    '      ),\n'
                                    '    ),\n'
                                    '    GoRoute(\n'
                                    "      path: '/coins',\n"
                                    '      builder: (_, __) => const CoinStoreScreen(),\n'
                                    '    ),\n'
                                    '  ],\n'
                                    ');\n',
 'apps/mobile/lib/src/theme.dart': "import 'package:flutter/material.dart';\n"
                                   '\n'
                                   'class VeezoTheme {\n'
                                   '  static ThemeData get light {\n'
                                   '    return ThemeData(\n'
                                   '      useMaterial3: true,\n'
                                   '      colorScheme: ColorScheme.fromSeed(\n'
                                   '        seedColor: const Color(0xFF5B35F5),\n'
                                   '        brightness: Brightness.light,\n'
                                   '      ),\n'
                                   '    );\n'
                                   '  }\n'
                                   '\n'
                                   '  static ThemeData get dark {\n'
                                   '    return ThemeData(\n'
                                   '      useMaterial3: true,\n'
                                   '      colorScheme: ColorScheme.fromSeed(\n'
                                   '        seedColor: const Color(0xFF5B35F5),\n'
                                   '        brightness: Brightness.dark,\n'
                                   '      ),\n'
                                   '    );\n'
                                   '  }\n'
                                   '}\n',
 'apps/mobile/pubspec.yaml': 'name: veezo_mfn\n'
                             'description: UAE live streaming and creator platform.\n'
                             'publish_to: "none"\n'
                             'version: 0.1.0+1\n'
                             '\n'
                             'environment:\n'
                             '  sdk: ">=3.4.0 <4.0.0"\n'
                             '\n'
                             'dependencies:\n'
                             '  flutter:\n'
                             '    sdk: flutter\n'
                             '  flutter_riverpod: ^2.6.1\n'
                             '  go_router: ^14.6.2\n'
                             '  dio: ^5.7.0\n'
                             '  shared_preferences: ^2.3.3\n'
                             '  flutter_secure_storage: ^9.2.2\n'
                             '  cached_network_image: ^3.4.1\n'
                             '  intl: ^0.20.1\n'
                             '\n'
                             'dev_dependencies:\n'
                             '  flutter_test:\n'
                             '    sdk: flutter\n'
                             '  flutter_lints: ^5.0.0\n'
                             '\n'
                             'flutter:\n'
                             '  uses-material-design: true\n',
 'database/schema.sql': 'CREATE EXTENSION IF NOT EXISTS "pgcrypto";\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS users (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    username VARCHAR(50) UNIQUE,\n'
                        '    display_name VARCHAR(100) NOT NULL,\n'
                        '    email VARCHAR(255) UNIQUE,\n'
                        '    phone VARCHAR(30) UNIQUE,\n'
                        '    avatar_url TEXT,\n'
                        "    country VARCHAR(2) DEFAULT 'AE',\n"
                        "    preferred_language VARCHAR(10) DEFAULT 'en',\n"
                        "    role VARCHAR(20) DEFAULT 'viewer',\n"
                        '    date_of_birth DATE,\n'
                        "    status VARCHAR(20) DEFAULT 'active',\n"
                        '    created_at TIMESTAMPTZ DEFAULT NOW(),\n'
                        '    updated_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS creators (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    user_id UUID UNIQUE NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n'
                        '    bio TEXT,\n'
                        "    verification_status VARCHAR(20) DEFAULT 'pending',\n"
                        '    live_enabled BOOLEAN DEFAULT FALSE,\n'
                        '    payout_enabled BOOLEAN DEFAULT FALSE,\n'
                        '    total_followers BIGINT DEFAULT 0,\n'
                        '    created_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS coin_wallets (\n'
                        '    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,\n'
                        '    purchased_balance BIGINT DEFAULT 0 CHECK (purchased_balance >= 0),\n'
                        '    bonus_balance BIGINT DEFAULT 0 CHECK (bonus_balance >= 0),\n'
                        '    updated_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS coin_transactions (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n'
                        '    transaction_type VARCHAR(40) NOT NULL,\n'
                        '    amount BIGINT NOT NULL,\n'
                        '    balance_after BIGINT,\n'
                        '    reference_id UUID,\n'
                        '    description TEXT,\n'
                        '    created_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS gifts (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    name VARCHAR(100) NOT NULL,\n'
                        '    slug VARCHAR(100) UNIQUE NOT NULL,\n'
                        '    coin_cost BIGINT NOT NULL CHECK (coin_cost > 0),\n'
                        '    creator_reward_units BIGINT NOT NULL DEFAULT 0,\n'
                        '    animation_url TEXT,\n'
                        '    thumbnail_url TEXT,\n'
                        '    category VARCHAR(50),\n'
                        '    active BOOLEAN DEFAULT TRUE,\n'
                        '    created_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS live_rooms (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    creator_id UUID NOT NULL REFERENCES creators(id) ON DELETE CASCADE,\n'
                        '    title VARCHAR(200),\n'
                        "    status VARCHAR(20) DEFAULT 'waiting',\n"
                        '    agora_channel VARCHAR(200),\n'
                        '    thumbnail_url TEXT,\n'
                        "    language VARCHAR(10) DEFAULT 'en',\n"
                        '    viewer_count INTEGER DEFAULT 0,\n'
                        '    started_at TIMESTAMPTZ,\n'
                        '    ended_at TIMESTAMPTZ,\n'
                        '    created_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS gift_transactions (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    sender_user_id UUID NOT NULL REFERENCES users(id),\n'
                        '    creator_user_id UUID NOT NULL REFERENCES users(id),\n'
                        '    live_room_id UUID REFERENCES live_rooms(id),\n'
                        '    gift_id UUID NOT NULL REFERENCES gifts(id),\n'
                        '    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),\n'
                        '    total_coins BIGINT NOT NULL CHECK (total_coins > 0),\n'
                        '    creator_reward_units BIGINT NOT NULL DEFAULT 0,\n'
                        '    created_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS creator_wallets (\n'
                        '    creator_id UUID PRIMARY KEY REFERENCES creators(id) ON DELETE CASCADE,\n'
                        '    pending_amount NUMERIC(12,2) DEFAULT 0 CHECK (pending_amount >= 0),\n'
                        '    available_amount NUMERIC(12,2) DEFAULT 0 CHECK (available_amount >= 0),\n'
                        '    lifetime_earnings NUMERIC(12,2) DEFAULT 0 CHECK (lifetime_earnings >= 0),\n'
                        "    currency VARCHAR(3) DEFAULT 'AED',\n"
                        '    updated_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS creator_earning_transactions (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    creator_id UUID NOT NULL REFERENCES creators(id),\n'
                        '    type VARCHAR(40) NOT NULL,\n'
                        '    gross_reward NUMERIC(12,2),\n'
                        '    amount NUMERIC(12,2) NOT NULL,\n'
                        "    status VARCHAR(20) DEFAULT 'pending',\n"
                        '    gift_transaction_id UUID REFERENCES gift_transactions(id),\n'
                        '    available_at TIMESTAMPTZ,\n'
                        '    created_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'CREATE TABLE IF NOT EXISTS reports (\n'
                        '    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),\n'
                        '    reporter_user_id UUID NOT NULL REFERENCES users(id),\n'
                        '    reported_user_id UUID REFERENCES users(id),\n'
                        '    live_room_id UUID REFERENCES live_rooms(id),\n'
                        '    reason VARCHAR(100) NOT NULL,\n'
                        '    details TEXT,\n'
                        "    status VARCHAR(20) DEFAULT 'open',\n"
                        '    created_at TIMESTAMPTZ DEFAULT NOW()\n'
                        ');\n'
                        '\n'
                        'INSERT INTO gifts (name, slug, coin_cost, creator_reward_units, category)\n'
                        'VALUES\n'
                        "('Heart', 'heart', 10, 2, 'popular'),\n"
                        "('Rose', 'rose', 50, 10, 'popular'),\n"
                        "('Coffee', 'coffee', 100, 20, 'popular'),\n"
                        "('Cake', 'cake', 250, 50, 'popular'),\n"
                        "('Diamond', 'diamond', 500, 100, 'premium'),\n"
                        "('Gift Box', 'gift-box', 1000, 200, 'premium'),\n"
                        "('Supercar', 'supercar', 5000, 1000, 'luxury'),\n"
                        "('Private Jet', 'private-jet', 15000, 3000, 'luxury')\n"
                        'ON CONFLICT (slug) DO NOTHING;\n',
 'docker-compose.yml': 'services:\n'
                       '  postgres:\n'
                       '    image: postgres:16\n'
                       '    container_name: veezo-postgres\n'
                       '    restart: unless-stopped\n'
                       '    environment:\n'
                       '      POSTGRES_DB: veezo\n'
                       '      POSTGRES_USER: veezo\n'
                       '      POSTGRES_PASSWORD: veezo_dev_password\n'
                       '    ports:\n'
                       '      - "5432:5432"\n'
                       '    volumes:\n'
                       '      - veezo_postgres_data:/var/lib/postgresql/data\n'
                       '      - ./database/schema.sql:/docker-entrypoint-initdb.d/001-schema.sql:ro\n'
                       '\n'
                       '  redis:\n'
                       '    image: redis:7-alpine\n'
                       '    container_name: veezo-redis\n'
                       '    restart: unless-stopped\n'
                       '    ports:\n'
                       '      - "6379:6379"\n'
                       '\n'
                       'volumes:\n'
                       '  veezo_postgres_data:\n',
 'docs/architecture.md': '# Veezo MFN Architecture\n'
                         '\n'
                         '## Core flow\n'
                         '\n'
                         '```text\n'
                         'Flutter App\n'
                         '   |\n'
                         '   v\n'
                         'API Gateway / NestJS API\n'
                         '   |\n'
                         '   +--> PostgreSQL\n'
                         '   +--> Redis\n'
                         '   +--> Agora token service\n'
                         '   +--> Payment verification\n'
                         '   +--> Moderation service\n'
                         '```\n'
                         '\n'
                         '## Trust model\n'
                         '\n'
                         'The mobile app must never decide:\n'
                         '- gift prices\n'
                         '- wallet balances\n'
                         '- creator payout rates\n'
                         '- payment verification result\n'
                         '- withdrawal status\n'
                         '\n'
                         'All value-changing operations are server-authoritative.\n'
                         '\n'
                         '## Wallet design\n'
                         '\n'
                         'Viewer balance and creator earnings are separate systems.\n'
                         '\n'
                         '### Viewer\n'
                         '- purchased coins\n'
                         '- bonus coins\n'
                         '- non-withdrawable\n'
                         '- usable only inside Veezo MFN\n'
                         '\n'
                         '### Creator\n'
                         '- separate pending earnings\n'
                         '- separate available earnings\n'
                         '- KYC before withdrawal\n'
                         '- payout hold period\n',
 'docs/compliance-checklist.md': '# UAE Launch Compliance Checklist\n'
                                 '\n'
                                 'Before accepting real money:\n'
                                 '\n'
                                 '- Confirm UAE trade licence activity covers operating the platform.\n'
                                 '- Obtain UAE legal review of virtual coins / gifts / creator earnings model.\n'
                                 '- Confirm whether CBUAE stored-value/payment regulation applies.\n'
                                 '- Finalize Terms of Service.\n'
                                 '- Finalize Privacy Policy.\n'
                                 '- Finalize Community Guidelines.\n'
                                 '- Finalize Creator Agreement.\n'
                                 '- Implement 18+ creator rule.\n'
                                 '- Implement KYC for creator withdrawals.\n'
                                 '- Implement report/block/moderation controls.\n'
                                 '- Add refund and chargeback handling.\n'
                                 '- Configure VAT and corporate-tax accounting with a UAE accountant.\n'
                                 '- Confirm UAE Media Council obligations for sponsored creator content.\n',
 'docs/roadmap.md': '# Product Roadmap\n'
                    '\n'
                    '## V0.1\n'
                    '- Email/phone login UI\n'
                    '- Discover feed\n'
                    '- Creator profile\n'
                    '- Fake live room\n'
                    '- Fake/test coins\n'
                    '- Gift tray\n'
                    '- Gift ledger\n'
                    '- Creator reward ledger\n'
                    '- Report/block UI\n'
                    '\n'
                    '## V0.2\n'
                    '- Agora live streaming\n'
                    '- Real-time chat\n'
                    '- Follow system\n'
                    '- Admin moderation dashboard\n'
                    '- Push notifications\n'
                    '\n'
                    '## V0.3\n'
                    '- Creator KYC\n'
                    '- Google Play Billing test\n'
                    '- Apple IAP test\n'
                    '- Stripe test checkout\n'
                    '- Refund handling\n'
                    '- Fraud controls\n'
                    '\n'
                    '## V1.0\n'
                    '- Production payments\n'
                    '- Creator payouts\n'
                    '- UAE launch\n'
                    '- Arabic/English/Hindi/Urdu/Malayalam\n',
 'infrastructure/README.md': '# Infrastructure\n'
                             '\n'
                             'V0.1 uses local Docker Compose for:\n'
                             '\n'
                             '- PostgreSQL\n'
                             '- Redis\n'
                             '\n'
                             'Future production deployment can use:\n'
                             '\n'
                             '- AWS RDS PostgreSQL\n'
                             '- AWS ElastiCache Redis\n'
                             '- AWS S3\n'
                             '- AWS ECS / App Runner / EKS\n'
                             '- CloudFront\n'
                             '- WAF\n'
                             '- Secrets Manager\n',
 'scripts/bootstrap.md': '# Manual GitHub Upload\n'
                         '\n'
                         '1. Download and extract the ZIP.\n'
                         '2. Create a new GitHub repository named `veezo-mfn-platform`.\n'
                         '3. Choose **Add file → Upload files**.\n'
                         '4. Upload the extracted project contents.\n'
                         '5. Commit to `main`.\n'
                         '\n'
                         'Recommended next:\n'
                         '\n'
                         '```bash\n'
                         'git checkout -b develop\n'
                         'git push -u origin develop\n'
                         '```\n'
                         '\n'
                         'For Flutter native platform generation:\n'
                         '\n'
                         '```bash\n'
                         'cd apps/mobile\n'
                         'flutter create --org ae.veezomfn --platforms=android,ios .\n'
                         'flutter pub get\n'
                         '```\n',
 'services/api/.env.example': 'PORT=8080\n'
                              'DATABASE_URL=postgresql://veezo:veezo_dev_password@localhost:5432/veezo\n'
                              'REDIS_URL=redis://localhost:6379\n'
                              '\n'
                              '# Add later:\n'
                              'AGORA_APP_ID=\n'
                              'AGORA_APP_CERTIFICATE=\n'
                              'JWT_SECRET=change-me-in-production\n'
                              'STRIPE_SECRET_KEY=\n',
 'services/api/package.json': '{\n'
                              '  "name": "@veezo/api",\n'
                              '  "version": "0.1.0",\n'
                              '  "private": true,\n'
                              '  "scripts": {\n'
                              '    "start": "node dist/main.js",\n'
                              '    "start:dev": "tsx watch src/main.ts",\n'
                              '    "build": "tsc -p tsconfig.json",\n'
                              '    "typecheck": "tsc --noEmit"\n'
                              '  },\n'
                              '  "dependencies": {\n'
                              '    "@fastify/cors": "^10.0.0",\n'
                              '    "dotenv": "^16.4.5",\n'
                              '    "fastify": "^5.2.1",\n'
                              '    "pg": "^8.13.1",\n'
                              '    "redis": "^4.7.0",\n'
                              '    "zod": "^3.24.1"\n'
                              '  },\n'
                              '  "devDependencies": {\n'
                              '    "@types/node": "^22.10.2",\n'
                              '    "@types/pg": "^8.11.10",\n'
                              '    "tsx": "^4.19.2",\n'
                              '    "typescript": "^5.7.2"\n'
                              '  }\n'
                              '}\n',
 'services/api/src/db.ts': 'import { Pool } from "pg";\n'
                           '\n'
                           'export const db = new Pool({\n'
                           '  connectionString: process.env.DATABASE_URL,\n'
                           '});\n',
 'services/api/src/main.ts': 'import "dotenv/config";\n'
                             'import Fastify from "fastify";\n'
                             'import cors from "@fastify/cors";\n'
                             'import { db } from "./db";\n'
                             '\n'
                             'const app = Fastify({ logger: true });\n'
                             '\n'
                             'await app.register(cors, {\n'
                             '  origin: true,\n'
                             '});\n'
                             '\n'
                             'app.get("/health", async () => ({\n'
                             '  ok: true,\n'
                             '  service: "veezo-mfn-api",\n'
                             '  version: "0.1.0"\n'
                             '}));\n'
                             '\n'
                             'app.get("/v1/gifts", async () => {\n'
                             '  const result = await db.query(\n'
                             '    `SELECT id, name, slug, coin_cost, creator_reward_units, category\n'
                             '     FROM gifts\n'
                             '     WHERE active = TRUE\n'
                             '     ORDER BY coin_cost ASC`\n'
                             '  );\n'
                             '\n'
                             '  return result.rows;\n'
                             '});\n'
                             '\n'
                             'app.get("/v1/live", async () => {\n'
                             '  const result = await db.query(\n'
                             '    `SELECT\n'
                             '       lr.id,\n'
                             '       lr.title,\n'
                             '       lr.language,\n'
                             '       lr.viewer_count,\n'
                             '       lr.status,\n'
                             '       u.display_name AS creator_name,\n'
                             '       u.avatar_url\n'
                             '     FROM live_rooms lr\n'
                             '     JOIN creators c ON c.id = lr.creator_id\n'
                             '     JOIN users u ON u.id = c.user_id\n'
                             "     WHERE lr.status = 'live'\n"
                             '     ORDER BY lr.viewer_count DESC`\n'
                             '  );\n'
                             '\n'
                             '  return result.rows;\n'
                             '});\n'
                             '\n'
                             'app.post("/v1/dev/seed-user", async () => {\n'
                             '  const client = await db.connect();\n'
                             '\n'
                             '  try {\n'
                             '    await client.query("BEGIN");\n'
                             '\n'
                             '    const userResult = await client.query(\n'
                             '      `INSERT INTO users (display_name, email, role)\n'
                             "       VALUES ('Demo Viewer', 'demo@veezo.local', 'viewer')\n"
                             '       ON CONFLICT (email)\n'
                             '       DO UPDATE SET display_name = EXCLUDED.display_name\n'
                             '       RETURNING id`\n'
                             '    );\n'
                             '\n'
                             '    const userId = userResult.rows[0].id;\n'
                             '\n'
                             '    await client.query(\n'
                             '      `INSERT INTO coin_wallets (user_id, purchased_balance, bonus_balance)\n'
                             '       VALUES ($1, 0, 100)\n'
                             '       ON CONFLICT (user_id)\n'
                             '       DO UPDATE SET bonus_balance = 100`,\n'
                             '      [userId]\n'
                             '    );\n'
                             '\n'
                             '    await client.query("COMMIT");\n'
                             '\n'
                             '    return { userId, bonusCoins: 100 };\n'
                             '  } catch (error) {\n'
                             '    await client.query("ROLLBACK");\n'
                             '    throw error;\n'
                             '  } finally {\n'
                             '    client.release();\n'
                             '  }\n'
                             '});\n'
                             '\n'
                             'const port = Number(process.env.PORT ?? 8080);\n'
                             '\n'
                             'app.listen({ port, host: "0.0.0.0" })\n'
                             '  .catch((error) => {\n'
                             '    app.log.error(error);\n'
                             '    process.exit(1);\n'
                             '  });\n',
 'services/api/tsconfig.json': '{\n'
                               '  "compilerOptions": {\n'
                               '    "target": "ES2022",\n'
                               '    "module": "CommonJS",\n'
                               '    "moduleResolution": "Node",\n'
                               '    "outDir": "dist",\n'
                               '    "rootDir": "src",\n'
                               '    "strict": true,\n'
                               '    "esModuleInterop": true,\n'
                               '    "skipLibCheck": true\n'
                               '  },\n'
                               '  "include": ["src/**/*.ts"]\n'
                               '}\n'}

def main():
    root = Path.cwd() / PROJECT_NAME
    root.mkdir(parents=True, exist_ok=True)

    for rel_path, content in FILES.items():
        path = root / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"created: {rel_path}")

    print()
    print(f"Veezo MFN repository generated at: {root}")
    print("Next:")
    print(f"  cd {PROJECT_NAME}")
    print("  git init")
    print("  git add .")
    print('  git commit -m "Initial Veezo MFN platform"')

if __name__ == "__main__":
    main()
